public class FlagNames
{
	//Autogenerated by FlagsEditor.cs. Do not change by hand. Nix pille!
	public class Flags
	{
		public const string TariToCaudden = "TariToCaudden";
		public const string NiceItGetsRenamed = "NiceItGetsRenamed";
		public const string WhatIsThis = "WhatIsThis";
	}
}
