public class FlagNames
{
	//Autogenerated by FlagsEditor.cs. Do not change by hand. Nix pille!
	public const string TariToCaudden = "TariToCaudden";
	public const string StartedGame = "StartedGame";

}
