public class FlagNames
{
	//Autogenerated by FlagsEditor.cs. Do not change by hand. Nix pille!
	public const string TariToCaudden = "TariToCaudden";
	public const string StartedGame = "StartedGame";
	public const string CearasStoryDone = "CearasStoryDone";
	public const string InTheInnWithTheWives = "InTheInnWithTheWives";
	public const string DeidresStoryDone = "DeidresStoryDone";
	public const string PernasStoryDone = "PernasStoryDone";
	public const string MikalsStoryDone = "MikalsStoryDone";
	public const string IllijsPastRevealed = "IllijsPastRevealed";
	public const string TheSagesStoryDone = "TheSagesStoryDone";
	public const string LirrasJourneyDone = "LirrasJourneyDone";
	public const string MaugesStoryDone = "MaugesStoryDone";

}
